[build]
pre-build = [
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.2/protoc-29.2-linux-x86_64.zip && unzip protoc-29.2-linux-x86_64.zip -d /usr/local && rm protoc-29.2-linux-x86_64.zip"
]

[build.env]
passthrough = ["RUSTFLAGS", "RUST_LOG"]
