name: CI

#--------------------------------------------------
# Workflow Triggers
#--------------------------------------------------
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]

#--------------------------------------------------
# Concurrency Control
#--------------------------------------------------
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

#--------------------------------------------------
# Jobs
#--------------------------------------------------
jobs:
  build:
    name: Build
    uses: ./.github/workflows/rust-build.yml
    with:
      rust-toolchain: "nightly-2025-10-05"
      packages: "tuic-server"
      target-config-file: ".github/target.toml"
      rustflags: "-Zthreads=8"

  release:
    name: Release
    needs: [build]
    uses: ./.github/workflows/release-publish.yml
    with:
      cliff-config: '.github/cliff.toml'
